//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.1 (entitiestodtos.codeplex.com).
//     Timestamp: 2013-10-25 - 09:52:24
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using OrderManagement.Web.Domain;
using OrderManagement.Web.Database;

namespace OrderManagement.Web.Domain
{

    /// <summary>
    /// Assembler for <see cref="tbl_Tags"/> and <see cref="tbl_Tags_DTO"/>.
    /// </summary>
    public static partial class tbl_Tags_Assembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="tbl_Tags_DTO"/> converted from <see cref="tbl_Tags"/>.</param>
        static partial void OnDTO(this tbl_Tags entity, tbl_Tags_DTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="tbl_Tags"/> converted from <see cref="tbl_Tags_DTO"/>.</param>
        static partial void OnEntity(this tbl_Tags_DTO dto, tbl_Tags entity);

        /// <summary>
        /// Converts this instance of <see cref="tbl_Tags_DTO"/> to an instance of <see cref="tbl_Tags"/>.
        /// </summary>
        /// <param name="dto"><see cref="tbl_Tags_DTO"/> to convert.</param>
        public static tbl_Tags ToEntity(this tbl_Tags_DTO dto)
        {
            if (dto == null) return null;

            var entity = new tbl_Tags();

            entity.TagId = dto.TagId;
            entity.TagName = dto.TagName;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="tbl_Tags"/> to an instance of <see cref="tbl_Tags_DTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="tbl_Tags"/> to convert.</param>
        public static tbl_Tags_DTO ToDTO(this tbl_Tags entity)
        {
            if (entity == null) return null;

            var dto = new tbl_Tags_DTO();

            dto.TagId = entity.TagId;
            dto.TagName = entity.TagName;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="tbl_Tags_DTO"/> to an instance of <see cref="tbl_Tags"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<tbl_Tags> ToEntities(this IEnumerable<tbl_Tags_DTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="tbl_Tags"/> to an instance of <see cref="tbl_Tags_DTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<tbl_Tags_DTO> ToDTOs(this IEnumerable<tbl_Tags> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
