//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015/01/18 - 22:03:43
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using OrderManagement.Web.Domain;
using OrderManagement.Web.Database;

namespace OrderManagement.Web.Domain.Assemblers
{

    /// <summary>
    /// Assembler for <see cref="tblEmployee"/> and <see cref="tblEmployeeDTO"/>.
    /// </summary>
    public static partial class tblEmployeeAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="tblEmployeeDTO"/> converted from <see cref="tblEmployee"/>.</param>
        static partial void OnDTO(this tblEmployee entity, tblEmployeeDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="tblEmployee"/> converted from <see cref="tblEmployeeDTO"/>.</param>
        static partial void OnEntity(this tblEmployeeDTO dto, tblEmployee entity);

        /// <summary>
        /// Converts this instance of <see cref="tblEmployeeDTO"/> to an instance of <see cref="tblEmployee"/>.
        /// </summary>
        /// <param name="dto"><see cref="tblEmployeeDTO"/> to convert.</param>
        public static tblEmployee ToEntity(this tblEmployeeDTO dto)
        {
            if (dto == null) return null;

            var entity = new tblEmployee();

            entity.EmployeeId = dto.EmployeeId;
            entity.FirstName = dto.FirstName;
            entity.LastName = dto.LastName;
            entity.JobTitle = dto.JobTitle;
            entity.MobileNo = dto.MobileNo;
            entity.Password = dto.Password;
            entity.OrganizationId = dto.OrganizationId;
            entity.IsPrimary = dto.IsPrimary;
            entity.CreationOn = dto.CreationOn;
            entity.ModifiedOn = dto.ModifiedOn;
            entity.IsActive = dto.IsActive;
            entity.DeviceId = dto.DeviceId;
            entity.DeviceType = dto.DeviceType;
            entity.DeviceToken = dto.DeviceToken;
            entity.IsDeleted = dto.IsDeleted;
            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="tblEmployee"/> to an instance of <see cref="tblEmployeeDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="tblEmployee"/> to convert.</param>
        public static tblEmployeeDTO ToDTO(this tblEmployee entity)
        {
            if (entity == null) return null;

            var dto = new tblEmployeeDTO();

            dto.EmployeeId = entity.EmployeeId;
            dto.FirstName = entity.FirstName;
            dto.LastName = entity.LastName;
            dto.JobTitle = entity.JobTitle;
            dto.MobileNo = entity.MobileNo;
            dto.Password = entity.Password;
            dto.OrganizationId = entity.OrganizationId;
            dto.IsPrimary = entity.IsPrimary;
            dto.CreationOn = entity.CreationOn;
            dto.ModifiedOn = entity.ModifiedOn;
            dto.IsActive = entity.IsActive;
            dto.DeviceId = entity.DeviceId;
            dto.DeviceType = entity.DeviceType;
            dto.DeviceToken = entity.DeviceToken;
            dto.IsDeleted = entity.IsDeleted;
            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="tblEmployeeDTO"/> to an instance of <see cref="tblEmployee"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<tblEmployee> ToEntities(this IEnumerable<tblEmployeeDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="tblEmployee"/> to an instance of <see cref="tblEmployeeDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<tblEmployeeDTO> ToDTOs(this IEnumerable<tblEmployee> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
