//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015/01/18 - 22:03:45
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using OrderManagement.Web.Domain;
using OrderManagement.Web.Database;

namespace OrderManagement.Web.Domain.Assemblers
{

    /// <summary>
    /// Assembler for <see cref="tblPayment"/> and <see cref="tblPaymentDTO"/>.
    /// </summary>
    public static partial class tblPaymentAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="tblPaymentDTO"/> converted from <see cref="tblPayment"/>.</param>
        static partial void OnDTO(this tblPayment entity, tblPaymentDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="tblPayment"/> converted from <see cref="tblPaymentDTO"/>.</param>
        static partial void OnEntity(this tblPaymentDTO dto, tblPayment entity);

        /// <summary>
        /// Converts this instance of <see cref="tblPaymentDTO"/> to an instance of <see cref="tblPayment"/>.
        /// </summary>
        /// <param name="dto"><see cref="tblPaymentDTO"/> to convert.</param>
        public static tblPayment ToEntity(this tblPaymentDTO dto)
        {
            if (dto == null) return null;

            var entity = new tblPayment();

            entity.PaymentId = dto.PaymentId;
            entity.OrganizationId = dto.OrganizationId;
            entity.Amount = dto.Amount;
            entity.NoofDays = dto.NoofDays;
            entity.CreationDate = dto.CreationDate;
            entity.Description = dto.Description;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="tblPayment"/> to an instance of <see cref="tblPaymentDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="tblPayment"/> to convert.</param>
        public static tblPaymentDTO ToDTO(this tblPayment entity)
        {
            if (entity == null) return null;

            var dto = new tblPaymentDTO();

            dto.PaymentId = entity.PaymentId;
            dto.OrganizationId = entity.OrganizationId;
            dto.Amount = entity.Amount;
            dto.NoofDays = entity.NoofDays;
            dto.CreationDate = entity.CreationDate;
            dto.Description = entity.Description;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="tblPaymentDTO"/> to an instance of <see cref="tblPayment"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<tblPayment> ToEntities(this IEnumerable<tblPaymentDTO> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="tblPayment"/> to an instance of <see cref="tblPaymentDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<tblPaymentDTO> ToDTOs(this IEnumerable<tblPayment> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
