//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderManagement.Web.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Category
    {
        public int CategoryId { get; set; }
        public string CatgeoryName { get; set; }
        public string AliasName { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreationDateTime { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
