//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderManagement.Web.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOrderStatu
    {
        public tblOrderStatu()
        {
            this.tblOrders = new HashSet<tblOrder>();
        }
    
        public int StatusId { get; set; }
        public string StatusName { get; set; }
    
        public virtual ICollection<tblOrder> tblOrders { get; set; }
    }
}
