//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderManagement.Web.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOrderItem
    {
        public int ItemId { get; set; }
        public Nullable<int> OrderId { get; set; }
        public string ItemName { get; set; }
        public Nullable<double> Quantity { get; set; }
        public string QuantityType { get; set; }
        public Nullable<int> Prority { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual tblOrder tblOrder { get; set; }
    }
}
