//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderManagement.Web.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOrder
    {
        public tblOrder()
        {
            this.tblOrderItems = new HashSet<tblOrderItem>();
        }
    
        public int OrderId { get; set; }
        public Nullable<System.DateTime> OrderDateTime { get; set; }
        public Nullable<int> RequesterLoginId { get; set; }
        public Nullable<int> RequesterOrganizationId { get; set; }
        public Nullable<int> RecieverOrganizationId { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<System.DateTime> LastStatusDateTime { get; set; }
        public Nullable<int> IsHandleByEmployeeId { get; set; }
    
        public virtual tblOrderStatu tblOrderStatu { get; set; }
        public virtual ICollection<tblOrderItem> tblOrderItems { get; set; }
    }
}
