//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderManagement.Web.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOrganization
    {
        public tblOrganization()
        {
            this.tblEmployees = new HashSet<tblEmployee>();
            this.tblPayments = new HashSet<tblPayment>();
        }
    
        public int OrganizationId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string JobTitle { get; set; }
        public Nullable<int> CityId { get; set; }
        public string OrganizationName { get; set; }
        public string Address { get; set; }
        public string MobileNo { get; set; }
        public string Latitute { get; set; }
        public string Logitute { get; set; }
        public string MapAddress { get; set; }
        public string EmailAddress { get; set; }
        public string OrganizationWebsite { get; set; }
        public Nullable<System.DateTime> CreationOn { get; set; }
        public Nullable<System.DateTime> ModificationOn { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsWorkingStatus { get; set; }
        public string IsWorkingStatusMessge { get; set; }
    
        public virtual tblCity tblCity { get; set; }
        public virtual ICollection<tblEmployee> tblEmployees { get; set; }
        public virtual ICollection<tblPayment> tblPayments { get; set; }
    }
}
