//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderManagement.Web.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPayment
    {
        public int PaymentId { get; set; }
        public Nullable<int> OrganizationId { get; set; }
        public string Amount { get; set; }
        public Nullable<int> NoofDays { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string Description { get; set; }
    
        public virtual tblOrganization tblOrganization { get; set; }
    }
}
