//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderManagement.Web.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSMSQueue
    {
        public int RowId { get; set; }
        public string MobileNo { get; set; }
        public string Message { get; set; }
        public Nullable<System.DateTime> CreationDateTime { get; set; }
    }
}
