//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.1 (entitiestodtos.codeplex.com).
//     Timestamp: 2013-10-10 - 10:49:51
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using OrderManagement.Web.Domain;
using System.ComponentModel.DataAnnotations;
using OrderManagement.Web.Domain.Resources;

namespace OrderManagement.Web.Domain
{
    [DataContract()]
    public partial class tbl_AdminLogin_DTO
    {
        [DataMember()]
        public Int32 AdminLoginId { get; set; }

        [DataMember(IsRequired = true)]
        [StringLength(50, ErrorMessageResourceName = "validationRange0To50", ErrorMessageResourceType = typeof(OrderManagementResource))]
        [RegularExpression(@"^[^<>`~}%:;^{*=|?]+$", ErrorMessageResourceName = "validationInvalidCharacters", ErrorMessageResourceType = typeof(OrderManagementResource))]
        [Display(ResourceType = typeof(OrderManagementResource), Name = "lblFirstName")]
        [Required(ErrorMessageResourceName = "validationRequiredFirstName", ErrorMessageResourceType = typeof(OrderManagementResource))]
        public String FirstName { get; set; }

        [DataMember(IsRequired = true)]
        [StringLength(50, ErrorMessageResourceName = "validationRange0To50", ErrorMessageResourceType = typeof(OrderManagementResource))]
        [RegularExpression(@"^[^<>`~}%:;^{*=|?]+$", ErrorMessageResourceName = "validationInvalidCharacters", ErrorMessageResourceType = typeof(OrderManagementResource))]
        [Display(ResourceType = typeof(OrderManagementResource), Name = "lblLastName")]
        [Required(ErrorMessageResourceName = "validationRequiredLastName", ErrorMessageResourceType = typeof(OrderManagementResource))]
        public String LastName { get; set; }

        [DataMember()]
        [Required(ErrorMessageResourceName = "validationRequiredUserName", ErrorMessageResourceType = typeof(OrderManagementResource))]
        [Display(ResourceType = typeof(OrderManagementResource), Name = "lblUserName")]
        public String UserName { get; set; }

        [DataMember(IsRequired = true)]
        [Display(ResourceType = typeof(OrderManagementResource), Name = "lblPassword")]
        [Required(ErrorMessageResourceName = "validationRequiredPassword", ErrorMessageResourceType = typeof(OrderManagementResource))]
        [DataType(DataType.Password)]
        public String Password { get; set; }

        [DataMember()]
        public Nullable<DateTime> RegisterDate { get; set; }

        [DataMember()]
        public Nullable<Byte> IsActive { get; set; }

    }
}
