//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.1 (entitiestodtos.codeplex.com).
//     Timestamp: 2013-10-25 - 09:52:23
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace OrderManagement.Web.Domain
{
    [DataContract()]
    public partial class tbl_Category_DTO
    {
        [DataMember()]
        public Int32 CategoryId { get; set; }

        [DataMember()]
        public String CatgeoryName { get; set; }

        [DataMember()]
        public String AliasName { get; set; }

        [DataMember()]
        public String Description { get; set; }

        [DataMember()]
        public Nullable<DateTime> CreationDateTime { get; set; }

        [DataMember()]
        public Nullable<Boolean> IsActive { get; set; }

    }
}
