//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015/01/18 - 22:07:30
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace OrderManagement.Web.Domain
{
    [DataContract()]
    public partial class tblAdminLoginDTO
    {
        [DataMember()]
        public Int32 AdminId { get; set; }

        [DataMember()]
        public String FirstName { get; set; }

        [DataMember()]
        public String LastName { get; set; }

        [DataMember()]
        public String UserName { get; set; }

        [DataMember()]
        public String Password { get; set; }

        [DataMember()]
        public Nullable<DateTime> RegisterDate { get; set; }

        [DataMember()]
        public Nullable<Boolean> IsActive { get; set; }

        public tblAdminLoginDTO()
        {
        }

        public tblAdminLoginDTO(Int32 adminId, String firstName, String lastName, String userName, String password, Nullable<DateTime> registerDate, Nullable<Boolean> isActive)
        {
			this.AdminId = adminId;
			this.FirstName = firstName;
			this.LastName = lastName;
			this.UserName = userName;
			this.Password = password;
			this.RegisterDate = registerDate;
			this.IsActive = isActive;
        }
    }
}
