//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015/01/18 - 22:03:39
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace OrderManagement.Web.Domain
{
    [DataContract()]
    public partial class tblCityDTO
    {
        [DataMember()]
        public Int32 CityId { get; set; }

        [DataMember()]
        public String CityName { get; set; }

        [DataMember()]
        public List<Int32> tblOrganizations_OrganizationId { get; set; }

        public tblCityDTO()
        {
        }

        public tblCityDTO(Int32 cityId, String cityName, List<Int32> tblOrganizations_OrganizationId)
        {
			this.CityId = cityId;
			this.CityName = cityName;
			this.tblOrganizations_OrganizationId = tblOrganizations_OrganizationId;
        }
    }
}
