//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015/01/18 - 22:03:39
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace OrderManagement.Web.Domain
{
    [DataContract()]
    public partial class tblEmployeeDTO
    {
        [DataMember()]
        public Int32 EmployeeId { get; set; }

        [DataMember()]
        public String FirstName { get; set; }

        [DataMember()]
        public String LastName { get; set; }

        [DataMember()]
        public String JobTitle { get; set; }

        [DataMember()]
        public String MobileNo { get; set; }

        [DataMember()]
        public String Password { get; set; }

        [DataMember()]
        public Nullable<Int32> OrganizationId { get; set; }

        [DataMember()]
        public String IsPrimary { get; set; }

        [DataMember()]
        public Nullable<DateTime> CreationOn { get; set; }

        [DataMember()]
        public Nullable<DateTime> ModifiedOn { get; set; }

        [DataMember()]
        public Nullable<Boolean> IsActive { get; set; }

        [DataMember()]
        public String DeviceId { get; set; }

        [DataMember()]
        public String DeviceType { get; set; }

        [DataMember()]
        public String DeviceToken { get; set; }

        [DataMember()]
        public Int32 tblOrganization_OrganizationId { get; set; }

        public tblEmployeeDTO()
        {
        }

        public tblEmployeeDTO(Int32 employeeId, String firstName, String lastName, String jobTitle, String mobileNo, String password, Nullable<Int32> organizationId, String isPrimary, Nullable<DateTime> creationOn, Nullable<DateTime> modifiedOn, Nullable<Boolean> isActive, String deviceId, String deviceType, String deviceToken, Int32 tblOrganization_OrganizationId)
        {
			this.EmployeeId = employeeId;
			this.FirstName = firstName;
			this.LastName = lastName;
			this.JobTitle = jobTitle;
			this.MobileNo = mobileNo;
			this.Password = password;
			this.OrganizationId = organizationId;
			this.IsPrimary = isPrimary;
			this.CreationOn = creationOn;
			this.ModifiedOn = modifiedOn;
			this.IsActive = isActive;
			this.DeviceId = deviceId;
			this.DeviceType = deviceType;
			this.DeviceToken = deviceToken;
			this.tblOrganization_OrganizationId = tblOrganization_OrganizationId;
        }
    }
}
