//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015/01/18 - 22:03:40
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace OrderManagement.Web.Domain
{
    [DataContract()]
    public partial class tblFavouriteOrganizationDTO
    {
        [DataMember()]
        public Int32 FavouriteId { get; set; }

        [DataMember()]
        public Nullable<Int32> FavOrganizationId { get; set; }

        [DataMember()]
        public Nullable<Int32> UserId { get; set; }

        [DataMember()]
        public Nullable<DateTime> CreationOn { get; set; }

        [DataMember()]
        public Nullable<DateTime> ModifiedOn { get; set; }

        public tblFavouriteOrganizationDTO()
        {
        }

        public tblFavouriteOrganizationDTO(Int32 favouriteId, Nullable<Int32> favOrganizationId, Nullable<Int32> userId, Nullable<DateTime> creationOn, Nullable<DateTime> modifiedOn)
        {
			this.FavouriteId = favouriteId;
			this.FavOrganizationId = favOrganizationId;
			this.UserId = userId;
			this.CreationOn = creationOn;
			this.ModifiedOn = modifiedOn;
        }
    }
}
