//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015/01/18 - 22:03:41
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace OrderManagement.Web.Domain
{
    [DataContract()]
    public partial class tblOrderStatuDTO
    {
        [DataMember()]
        public Int32 StatusId { get; set; }

        [DataMember()]
        public String StatusName { get; set; }

        [DataMember()]
        public List<Int32> tblOrders_OrderId { get; set; }

        public tblOrderStatuDTO()
        {
        }

        public tblOrderStatuDTO(Int32 statusId, String statusName, List<Int32> tblOrders_OrderId)
        {
			this.StatusId = statusId;
			this.StatusName = statusName;
			this.tblOrders_OrderId = tblOrders_OrderId;
        }
    }
}
