//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015/01/18 - 22:03:42
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;
using OrderManagement.Web.Domain.Resources;
namespace OrderManagement.Web.Domain
{
    [DataContract()]
    public partial class tblOrganizationDTO
    {
        [DataMember()]
        public Int32 OrganizationId { get; set; }

        [DataMember()]
        [Required(ErrorMessageResourceType = typeof(OrderManagementResource), ErrorMessageResourceName = "validationRequiredFirstName")]
        [StringLength(255, ErrorMessageResourceName = "validationRange0To255", ErrorMessageResourceType = typeof(OrderManagementResource))]
        public String FirstName { get; set; }

        [DataMember()]
        [Required(ErrorMessageResourceType = typeof(OrderManagementResource), ErrorMessageResourceName = "validationRequiredLastName")]
        [StringLength(255, ErrorMessageResourceName = "validationRange0To255", ErrorMessageResourceType = typeof(OrderManagementResource))]
        public String LastName { get; set; }

        [DataMember()]
        public String JobTitle { get; set; }

        [DataMember()]
        public Nullable<Int32> CityId { get; set; }

        [DataMember()]
        [Required(ErrorMessageResourceType = typeof(OrderManagementResource), ErrorMessageResourceName = "validationRequiredOrganizationName")]
        [StringLength(255, ErrorMessageResourceName = "validationRange0To255", ErrorMessageResourceType = typeof(OrderManagementResource))]
        public String OrganizationName { get; set; }

        [DataMember()]
        public String Address { get; set; }

        [DataMember()]
        [Required(ErrorMessageResourceType = typeof(OrderManagementResource), ErrorMessageResourceName = "validationRequiredMobileNo")]
        public String MobileNo { get; set; }

        [DataMember()]
        public String Latitute { get; set; }

        [DataMember()]
        public String Logitute { get; set; }

        [DataMember()]
        public String MapAddress { get; set; }

        [DataMember()]
        public String EmailAddress { get; set; }

        [DataMember()]
        public String OrganizationWebsite { get; set; }

        [DataMember()]
        public Nullable<DateTime> CreationOn { get; set; }

        [DataMember()]
        public String ModificationOn { get; set; }

        [DataMember()]
        public Nullable<Boolean> IsActive { get; set; }

        [DataMember()]
        public Nullable<Boolean> IsWorkingStatus { get; set; }

        [DataMember()]
        public String IsWorkingStatusMessge { get; set; }

        [DataMember()]
        public Int32 tblCity_CityId { get; set; }

        [DataMember()]
        public List<Int32> tblEmployees_EmployeeId { get; set; }

        [DataMember()]
        public List<Int32> tblPayments_PaymentId { get; set; }

        public tblOrganizationDTO()
        {
        }

        public tblOrganizationDTO(Int32 organizationId, String firstName, String lastName, String jobTitle, Nullable<Int32> cityId, String organizationName, String address, String mobileNo, String latitute, String logitute, String mapAddress, String emailAddress, String organizationWebsite, Nullable<DateTime> creationOn, String modificationOn, Nullable<Boolean> isActive, Nullable<Boolean> isWorkingStatus, String isWorkingStatusMessge, Int32 tblCity_CityId, List<Int32> tblEmployees_EmployeeId, List<Int32> tblPayments_PaymentId)
        {
			this.OrganizationId = organizationId;
			this.FirstName = firstName;
			this.LastName = lastName;
			this.JobTitle = jobTitle;
			this.CityId = cityId;
			this.OrganizationName = organizationName;
			this.Address = address;
			this.MobileNo = mobileNo;
			this.Latitute = latitute;
			this.Logitute = logitute;
			this.MapAddress = mapAddress;
			this.EmailAddress = emailAddress;
			this.OrganizationWebsite = organizationWebsite;
			this.CreationOn = creationOn;
			this.ModificationOn = modificationOn;
			this.IsActive = isActive;
			this.IsWorkingStatus = isWorkingStatus;
			this.IsWorkingStatusMessge = isWorkingStatusMessge;
			this.tblCity_CityId = tblCity_CityId;
			this.tblEmployees_EmployeeId = tblEmployees_EmployeeId;
			this.tblPayments_PaymentId = tblPayments_PaymentId;
        }
    }
}
