//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015/01/18 - 22:03:42
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;
using OrderManagement.Web.Domain.Resources;
namespace OrderManagement.Web.Domain
{
    [DataContract()]
    public partial class tblOrganizationDTO : CommonModel
    {
        [DataMember()]
        public Int32 OrganizationId { get; set; }

        [DataMember()]
        [Required(ErrorMessageResourceType = typeof(OrderManagementResource), ErrorMessageResourceName = "validationRequiredFirstName")]
        [StringLength(255, ErrorMessageResourceName = "validationRange0To255", ErrorMessageResourceType = typeof(OrderManagementResource))]
        public String FirstName { get; set; }

        [DataMember()]
        [Required(ErrorMessageResourceType = typeof(OrderManagementResource), ErrorMessageResourceName = "validationRequiredLastName")]
        [StringLength(255, ErrorMessageResourceName = "validationRange0To255", ErrorMessageResourceType = typeof(OrderManagementResource))]
        public String LastName { get; set; }

        [DataMember()]
        public String JobTitle { get; set; }

        [DataMember()]
        public Nullable<Int32> CityId { get; set; }

        [DataMember()]
        [Required(ErrorMessageResourceType = typeof(OrderManagementResource), ErrorMessageResourceName = "validationRequiredOrganizationName")]
        [StringLength(255, ErrorMessageResourceName = "validationRange0To255", ErrorMessageResourceType = typeof(OrderManagementResource))]
        public String OrganizationName { get; set; }

        [DataMember()]
        public String Address { get; set; }

        [DataMember()]
        [Required(ErrorMessageResourceType = typeof(OrderManagementResource), ErrorMessageResourceName = "validationRequiredMobileNo")]
        [StringLength(10, MinimumLength = 10, ErrorMessageResourceName = "validationMobileNo", ErrorMessageResourceType = typeof(OrderManagementResource))]
        [RegularExpression(RegularExpressionString.RegularMobileNo, ErrorMessageResourceName = "validationRegularMobileNo", ErrorMessageResourceType = typeof(OrderManagementResource))]
        public String MobileNo { get; set; }

        [DataMember()]
        public String Latitute { get; set; }

        [DataMember()]
        public String Logitute { get; set; }

        [DataMember()]
        public String MapAddress { get; set; }

        [DataMember()]
        public String EmailAddress { get; set; }

        [DataMember()]
        public String OrganizationWebsite { get; set; }

        [DataMember()]
        public Nullable<DateTime> CreationOn { get; set; }

        [DataMember()]
        public Nullable<DateTime> ModificationOn { get; set; }

        [DataMember()]
        public Nullable<Boolean> IsActive { get; set; }

        [DataMember()]
        public Nullable<Boolean> IsWorkingStatus { get; set; }

        [DataMember()]
        public String IsWorkingStatusMessge { get; set; }

        [DataMember()]
        public Int32 tblCity_CityId { get; set; }

        [DataMember()]
        public List<Int32> tblEmployees_EmployeeId { get; set; }

        [DataMember()]
        public List<Int32> tblPayments_PaymentId { get; set; }

        //[DataMember]
        //[Required(ErrorMessageResourceType = typeof(OrderManagementResource), ErrorMessageResourceName = "validationRequiredPassword")]
        //[StringLength(12, MinimumLength = 4, ErrorMessageResourceName = "validationPasswordRangeBetween4To12", ErrorMessageResourceType = typeof(OrderManagementResource))]
        //[DataType(DataType.Password)]
        public string Password { get; set; }
    }
}
