//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015/01/18 - 22:03:41
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace OrderManagement.Web.Domain
{
    [DataContract()]
    public partial class tblOrderItemDTO
    {
        [DataMember()]
        public Int32 ItemId { get; set; }

        [DataMember()]
        public Nullable<Int32> OrderId { get; set; }

        [DataMember()]
        public String ItemName { get; set; }

        [DataMember()]
        public Nullable<Double> Quantity { get; set; }

        [DataMember()]
        public String QuantityType { get; set; }

        [DataMember()]
        public Nullable<Int32> Prority { get; set; }

        [DataMember()]
        public Nullable<Int32> Status { get; set; }

        [DataMember()]
        public Int32 tblOrder_OrderId { get; set; }

        public tblOrderItemDTO()
        {
        }

        public tblOrderItemDTO(Int32 itemId, Nullable<Int32> orderId, String itemName, Nullable<Double> quantity, String quantityType, Nullable<Int32> prority, Nullable<Int32> status, Int32 tblOrder_OrderId)
        {
			this.ItemId = itemId;
			this.OrderId = orderId;
			this.ItemName = itemName;
			this.Quantity = quantity;
			this.QuantityType = quantityType;
			this.Prority = prority;
			this.Status = status;
			this.tblOrder_OrderId = tblOrder_OrderId;
        }
    }
}
