//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2015/01/18 - 22:03:43
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace OrderManagement.Web.Domain
{
    [DataContract()]
    public partial class tblPaymentDTO
    {
        [DataMember()]
        public Int32 PaymentId { get; set; }

        [DataMember()]
        public Nullable<Int32> OrganizationId { get; set; }

        [DataMember()]
        public String Amount { get; set; }

        [DataMember()]
        public Nullable<Int32> NoofDays { get; set; }

        [DataMember()]
        public Nullable<DateTime> CreationDate { get; set; }

        [DataMember()]
        public String Description { get; set; }

        [DataMember()]
        public Int32 tblOrganization_OrganizationId { get; set; }

        public tblPaymentDTO()
        {
        }

        public tblPaymentDTO(Int32 paymentId, Nullable<Int32> organizationId, String amount, Nullable<Int32> noofDays, Nullable<DateTime> creationDate, String description, Int32 tblOrganization_OrganizationId)
        {
			this.PaymentId = paymentId;
			this.OrganizationId = organizationId;
			this.Amount = amount;
			this.NoofDays = noofDays;
			this.CreationDate = creationDate;
			this.Description = description;
			this.tblOrganization_OrganizationId = tblOrganization_OrganizationId;
        }
    }
}
