//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderManagement.Web.BLL.AdminService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OrderManagement.Web.BLL.AdminService.IAdminService")]
    public interface IAdminService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/GetAdminLoginDetail", ReplyAction="http://tempuri.org/IAdminService/GetAdminLoginDetailResponse")]
        OrderManagement.Web.Domain.ServiceResult<OrderManagement.Web.Domain.tblAdminLoginDTO> GetAdminLoginDetail(OrderManagement.Web.Domain.tblAdminLoginDTO tbl_AdminLogin_DTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/GetAdminLoginDetail", ReplyAction="http://tempuri.org/IAdminService/GetAdminLoginDetailResponse")]
        System.Threading.Tasks.Task<OrderManagement.Web.Domain.ServiceResult<OrderManagement.Web.Domain.tblAdminLoginDTO>> GetAdminLoginDetailAsync(OrderManagement.Web.Domain.tblAdminLoginDTO tbl_AdminLogin_DTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/GetBoolData", ReplyAction="http://tempuri.org/IAdminService/GetBoolDataResponse")]
        bool GetBoolData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdminService/GetBoolData", ReplyAction="http://tempuri.org/IAdminService/GetBoolDataResponse")]
        System.Threading.Tasks.Task<bool> GetBoolDataAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAdminServiceChannel : OrderManagement.Web.BLL.AdminService.IAdminService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AdminServiceClient : System.ServiceModel.ClientBase<OrderManagement.Web.BLL.AdminService.IAdminService>, OrderManagement.Web.BLL.AdminService.IAdminService
    {
        
        public AdminServiceClient()
        {
        }
        
        public AdminServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public AdminServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public AdminServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public AdminServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public OrderManagement.Web.Domain.ServiceResult<OrderManagement.Web.Domain.tblAdminLoginDTO> GetAdminLoginDetail(OrderManagement.Web.Domain.tblAdminLoginDTO tbl_AdminLogin_DTO)
        {
            return base.Channel.GetAdminLoginDetail(tbl_AdminLogin_DTO);
        }
        
        public System.Threading.Tasks.Task<OrderManagement.Web.Domain.ServiceResult<OrderManagement.Web.Domain.tblAdminLoginDTO>> GetAdminLoginDetailAsync(OrderManagement.Web.Domain.tblAdminLoginDTO tbl_AdminLogin_DTO)
        {
            return base.Channel.GetAdminLoginDetailAsync(tbl_AdminLogin_DTO);
        }
        
        public bool GetBoolData()
        {
            return base.Channel.GetBoolData();
        }
        
        public System.Threading.Tasks.Task<bool> GetBoolDataAsync()
        {
            return base.Channel.GetBoolDataAsync();
        }
    }
}
