//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderManagement.Web.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OrderManagementResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OrderManagementResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OrderManagement.Web.Domain.Resources.OrderManagementResource", typeof(OrderManagementResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save &amp; close.
        /// </summary>
        public static string btnSaveAndClose {
            get {
                return ResourceManager.GetString("btnSaveAndClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save &amp; continue.
        /// </summary>
        public static string btnSaveAndContinue {
            get {
                return ResourceManager.GetString("btnSaveAndContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsActive.
        /// </summary>
        public static string IsActive {
            get {
                return ResourceManager.GetString("IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string lblActive {
            get {
                return ResourceManager.GetString("lblActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alias Name.
        /// </summary>
        public static string lblAliasName {
            get {
                return ResourceManager.GetString("lblAliasName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        public static string lblAvailable {
            get {
                return ResourceManager.GetString("lblAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string lblCancel {
            get {
                return ResourceManager.GetString("lblCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catgeory List.
        /// </summary>
        public static string lblCategoryList {
            get {
                return ResourceManager.GetString("lblCategoryList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Name.
        /// </summary>
        public static string lblCategoryName {
            get {
                return ResourceManager.GetString("lblCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string lblCreate {
            get {
                return ResourceManager.GetString("lblCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Account.
        /// </summary>
        public static string lblCreateAccount {
            get {
                return ResourceManager.GetString("lblCreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation Datetime.
        /// </summary>
        public static string lblCreationDate {
            get {
                return ResourceManager.GetString("lblCreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string lblDelete {
            get {
                return ResourceManager.GetString("lblDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string lblDescription {
            get {
                return ResourceManager.GetString("lblDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string lblEdit {
            get {
                return ResourceManager.GetString("lblEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string lblFirstName {
            get {
                return ResourceManager.GetString("lblFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password.
        /// </summary>
        public static string lblForgotPassword {
            get {
                return ResourceManager.GetString("lblForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string lblGender {
            get {
                return ResourceManager.GetString("lblGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        public static string lblInactive {
            get {
                return ResourceManager.GetString("lblInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string lblLastName {
            get {
                return ResourceManager.GetString("lblLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string lblLogin {
            get {
                return ResourceManager.GetString("lblLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please login with your Username and Password..
        /// </summary>
        public static string lblLoginPageTitle {
            get {
                return ResourceManager.GetString("lblLoginPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile No.
        /// </summary>
        public static string lblMobileNo {
            get {
                return ResourceManager.GetString("lblMobileNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization Name.
        /// </summary>
        public static string lblOrganizationName {
            get {
                return ResourceManager.GetString("lblOrganizationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string lblPassword {
            get {
                return ResourceManager.GetString("lblPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demo.
        /// </summary>
        public static string lblProjectTitle {
            get {
                return ResourceManager.GetString("lblProjectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string lblRegister {
            get {
                return ResourceManager.GetString("lblRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Success.
        /// </summary>
        public static string lblRegisterSuccess {
            get {
                return ResourceManager.GetString("lblRegisterSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Me.
        /// </summary>
        public static string lblRememberMe {
            get {
                return ResourceManager.GetString("lblRememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-type Password.
        /// </summary>
        public static string lblReTypePassword {
            get {
                return ResourceManager.GetString("lblReTypePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string lblSave {
            get {
                return ResourceManager.GetString("lblSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string lblSubmit {
            get {
                return ResourceManager.GetString("lblSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string lblUserName {
            get {
                return ResourceManager.GetString("lblUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string lblView {
            get {
                return ResourceManager.GetString("lblView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete category..
        /// </summary>
        public static string msgConfirmDeleteCategory {
            get {
                return ResourceManager.GetString("msgConfirmDeleteCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account is disabled please contact admin for more details..
        /// </summary>
        public static string msgDiableUserAccount {
            get {
                return ResourceManager.GetString("msgDiableUserAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The username or password you entered is incorrect..
        /// </summary>
        public static string msgIncorrectUserNameAndPassword {
            get {
                return ResourceManager.GetString("msgIncorrectUserNameAndPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile no already exists please delete your mobile from last organization then you can continue using this..
        /// </summary>
        public static string msgMobileNoExists {
            get {
                return ResourceManager.GetString("msgMobileNoExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are register successfully with us. Login your self and get benift with us..
        /// </summary>
        public static string msgRegisterSuccess {
            get {
                return ResourceManager.GetString("msgRegisterSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter must be 10 characters number..
        /// </summary>
        public static string validationMobileNo {
            get {
                return ResourceManager.GetString("validationMobileNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter password between 4 and 12..
        /// </summary>
        public static string validationPasswordRangeBetween4To12 {
            get {
                return ResourceManager.GetString("validationPasswordRangeBetween4To12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter maximum 100 characters..
        /// </summary>
        public static string validationRange0To100 {
            get {
                return ResourceManager.GetString("validationRange0To100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter maximum 1000 characters..
        /// </summary>
        public static string validationRange0To1000 {
            get {
                return ResourceManager.GetString("validationRange0To1000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter maximum 1024 characters..
        /// </summary>
        public static string validationRange0To1024 {
            get {
                return ResourceManager.GetString("validationRange0To1024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter maximum 200 characters..
        /// </summary>
        public static string validationRange0To200 {
            get {
                return ResourceManager.GetString("validationRange0To200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter maximum 250 characters..
        /// </summary>
        public static string validationRange0To250 {
            get {
                return ResourceManager.GetString("validationRange0To250", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter maximum 255 characters..
        /// </summary>
        public static string validationRange0To255 {
            get {
                return ResourceManager.GetString("validationRange0To255", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter maximum 400 characters..
        /// </summary>
        public static string validationRange0To400 {
            get {
                return ResourceManager.GetString("validationRange0To400", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter maximum 50 characters..
        /// </summary>
        public static string validationRange0To50 {
            get {
                return ResourceManager.GetString("validationRange0To50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter maximum 500 characters..
        /// </summary>
        public static string validationRange0To500 {
            get {
                return ResourceManager.GetString("validationRange0To500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter maximum 5000 characters..
        /// </summary>
        public static string validationRange0To5000 {
            get {
                return ResourceManager.GetString("validationRange0To5000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter number between 1 and 20..
        /// </summary>
        public static string validationRangeBetween1To20 {
            get {
                return ResourceManager.GetString("validationRangeBetween1To20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter number between 1 and 999..
        /// </summary>
        public static string validationRangeBetween1To999 {
            get {
                return ResourceManager.GetString("validationRangeBetween1To999", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter number between 2 and 15..
        /// </summary>
        public static string validationRangeBetween2To15 {
            get {
                return ResourceManager.GetString("validationRangeBetween2To15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter number between 2 and 20..
        /// </summary>
        public static string validationRangeBetween2To20 {
            get {
                return ResourceManager.GetString("validationRangeBetween2To20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter minimum 3 and maxumum 50 characters..
        /// </summary>
        public static string validationRangeCharacters3To50 {
            get {
                return ResourceManager.GetString("validationRangeCharacters3To50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter number greater than 0..
        /// </summary>
        public static string validationRangeGreaterThenZero {
            get {
                return ResourceManager.GetString("validationRangeGreaterThenZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid mobile no value must contain 10 value size..
        /// </summary>
        public static string validationRegularMobileNo {
            get {
                return ResourceManager.GetString("validationRegularMobileNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter comment..
        /// </summary>
        public static string validationRequiredComment {
            get {
                return ResourceManager.GetString("validationRequiredComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter email account password..
        /// </summary>
        public static string validationRequiredEmailAccountPassword {
            get {
                return ResourceManager.GetString("validationRequiredEmailAccountPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter email account username..
        /// </summary>
        public static string validationRequiredEmailAccountUserName {
            get {
                return ResourceManager.GetString("validationRequiredEmailAccountUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter email address..
        /// </summary>
        public static string validationRequiredEmailAddress {
            get {
                return ResourceManager.GetString("validationRequiredEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter first name..
        /// </summary>
        public static string validationRequiredFirstName {
            get {
                return ResourceManager.GetString("validationRequiredFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter last name..
        /// </summary>
        public static string validationRequiredLastName {
            get {
                return ResourceManager.GetString("validationRequiredLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter maximum password life..
        /// </summary>
        public static string validationRequiredMaxPasswordLife {
            get {
                return ResourceManager.GetString("validationRequiredMaxPasswordLife", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter minimum password length..
        /// </summary>
        public static string validationRequiredMinPasswordLength {
            get {
                return ResourceManager.GetString("validationRequiredMinPasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter minimum quontom of check..
        /// </summary>
        public static string validationRequiredMinQuontomOfCheck {
            get {
                return ResourceManager.GetString("validationRequiredMinQuontomOfCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter mobile no..
        /// </summary>
        public static string validationRequiredMobileNo {
            get {
                return ResourceManager.GetString("validationRequiredMobileNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter new password..
        /// </summary>
        public static string validationRequiredNewPassword {
            get {
                return ResourceManager.GetString("validationRequiredNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter organization name..
        /// </summary>
        public static string validationRequiredOrganizationName {
            get {
                return ResourceManager.GetString("validationRequiredOrganizationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter password..
        /// </summary>
        public static string validationRequiredPassword {
            get {
                return ResourceManager.GetString("validationRequiredPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter username..
        /// </summary>
        public static string validationRequiredUserName {
            get {
                return ResourceManager.GetString("validationRequiredUserName", resourceCulture);
            }
        }
    }
}
